import type { Metadata } from "next";

export const links = {
  sourceCode: "https://github.com/ELMACHHOUNE/next-js-portfolio",
  ownerName: "MOHAMED EL MACHHOUNE",
  ownerEmail: "business.elmachhoune@gmail.com",
} as const;

export const siteConfig: Metadata = {
  title: `${links.ownerName}`,
  description: "Mohamed El Machhoune's Modern & Minimalist Portfolio showcasing expertise in Full-Stack Development with the MERN stack, UX/UI Design, Instruction, and Consulting.",
  keywords: [
    "elmachhoune",
    "ELMACHHOUNE",
    "MOHAMED EL MACHHOUNE",
    "mohamed el machhoune",
    "el machhoune",
    "el machhoune mohamed",
    "elmachon mohamed",
    "elmachhon",
    "elmachhoun",
    "mohamed-el-machhoune",
    "med el machhoune",
    "gotodev",
    "MR TECHNOLOGIES",
    "mr-technologies",
    "devloper",
    "developpement darija maroc",
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "aceternity",
    "aceternity-ui",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "modern-portfolio",
    "portfolio",
    "3d-portfolio",
    "animated-portfolio",
    "nextjs-portfolio",
    "react-portfolio",
    "react-three-fiber",
    "three.js",
    "animated-website",
    "framer",
    "framer-motion",
    "three",
    "react-icons",
    "lucide-react",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: links.ownerName,
    url: "https://github.com/ELMACHHOUNE/",
  },
} as const;
